#!/bin/bash

curl ifconfig.me > new_ip.txt

if (source venv/bin/activate) ; then
    source venv/bin/activate
    echo "Venv Activated..."
else 
    python -m venv venv 
    source venv/bin/activate
    pip install -r requirements.txt
    cd ..
    echo "Venv Activated..."
fi

# add the python file.py here 
python3 check.py
